#!/bin/bash

set -x

# systemctl mask jobs will force disable these units by linking them to /dev/null
MASK_JOBS="sys-fs-fuse-connections.mount systemd-initctl.socket getty.target"
systemctl mask ${MASK_JOBS}
for i in ${MASK_JOBS};do find /usr/lib/systemd/ -iname $i | grep ".wants" | xargs rm -f; done
rm -f /etc/fstab
cp -p /usr/lib/systemd/systemd /usr/lib/systemd/systemd-starter
chmod 6550 /usr/lib/systemd/systemd-starter
ln -fs ${SYSTEMD_APP_ROOT}/bin/systemd_entrypoint /sbin/init
