#!/bin/bash
set -x
useradd -l -u ${USER_UID} -r -g 0 -d ${SYSTEMD_APP_ROOT} -s /sbin/nologin -c "${USER_NAME} application user" ${USER_NAME}
chown -R ${USER_UID}:0 ${SYSTEMD_APP_ROOT}
find ${SYSTEMD_APP_ROOT} -type d -exec chmod g+x {} +
chmod -R g+w ${SYSTEMD_APP_ROOT} /etc/passwd